### ISSUE TITLE
Use poll instead of select on platforms where it's available

### ISSUE THREAD

**Issue by mmikulicic** [cesanta/fossa#113]
See cesanta/mongoose#439

**Comment by cpq** [comment]
Rojer, please take this over.
Consider abstracting polling API and make it easy to use different multiplexing methods, like poll, epoll, kqueue.

**Comment by schmurfy** [comment]
I might be completely wrong on that but from my understanding select is more eficient for small number of descriptors and after  certain threshold epool/kqueue take the lead. If that is the case select might be more appropriate in the use case I would use this library (small embedded systems won't handle thousands of connections).

**Comment by rojer** [comment]
poll() is cumbersome. https://github.com/cesanta/fossa/commit/3a54681ff30542fe1b9075b77f1b66b5f775be64 added support for epoll on linux, and refactoring has been done to make adding support for other mechanisms easier.
