### ISSUE TITLE
json library conflict

### ISSUE THREAD

**Issue by criptanet** [cesanta/fossa#185]
Fossa wanted to integrate my application.
Now I use a JSON library (libjson0-dev).
I get conflict with:
- "json_object.h:92:14: error: previous definition here typedef enum json_type" 
and 
-"fossa.h:402:6: error: multiple definition of ‘enum json_type’"

any way to fix?
very good job.
congratulations

**Comment by NLxAROSA** [comment]
It has a JSON parser/generator already built in: https://github.com/cesanta/frozen

I guess you could either use that or rip it out.

**Comment by cpq** [comment]
I suggest to use fossa's JSON functionality.
Or, as Lars pointed out, rip it out.
