### ISSUE TITLE
Port fossa to Arduino Mega

### ISSUE THREAD

**Issue by cpq** [cesanta/fossa#199]
Create a shim layer for Arduino that implements async socket IO.
Create a sketch that periodically reports some data to the remote server using fossa.
Organize that sketch as a tutorial on how to use fossa on arduino, add it to fossa/examples

**Comment by alashkin** [comment]
All required PR's were merged.
Results:
1. Fossa works on Arduino Mega 
2. W5100 (ethernet shield) and CC3000 (wifi) are supported
3. There are two examples: ardunino_restsul_server and arduino_restful_client. Instructions were put into headers of .ino files (it could be copy'n'pasted into separated files, but other samples put its descriptions into headers)

**Comment by cpq** [comment]
Please put instructions into the README.md files in the respective dirs
