### ISSUE TITLE
File descriptors are not closed after the end of http client query

### ISSUE THREAD

**Issue by iheb-eddine** [cesanta/fossa#229]
Hello,

I created a client and server programs using fossa for my company project.
If we send a http get query to my fossa server, after the query is finished all the file descriptors opened by fossa are closed.
But when I send HTTP-GET query to an online server for example google.com, I found new file descriptors are opened and they won't be closed even after a big period from executing that query.
I use this command to find the number of opened file descriptors for my process:  ls /proc/pid/fd/ | wc -w

I used this simple program to reproduce this problem, you will find at the end of the program 100 new file descriptors are opened:

```c
static int s_exit_flag = 0;
static int s_show_headers = 0;

int send_http_query();

int main()
{
  for (int i = 1; i <= 100; i++)
  {
      send_http_query();
  }

  //You can call the cammand "ls /proc/pid/fd/ | wc -w" while it is sleeping, you will find 100 new file descriptors are still opened
  sleep(1000);

  return 0;
}

static void ev_handler(struct ns_connection *nc, int ev, void *ev_data) {
  struct http_message *hm = (struct http_message *) ev_data;

  switch (ev) {
    case NS_CONNECT:
      if (* (int *) ev_data != 0) {
        fprintf(stderr, "connect() failed: %s\n", strerror(* (int *) ev_data));
        s_exit_flag = 1;
      }
      break;
    case NS_HTTP_REPLY:
      nc->flags |= NSF_CLOSE_IMMEDIATELY;
      fwrite(hm->body.p, 1, hm->body.len, stdout);
      putchar('\n');
      s_exit_flag = 1;
      break;
    default:
      break;
  }
}

int send_http_query()
{
  struct ns_mgr mgr;

  ns_mgr_init(&mgr, NULL);

  /* Process command line arguments */
  s_show_headers = 1;

  ns_connect_http(&mgr, ev_handler, (char *)"google.com", NULL);

  while (s_exit_flag == 0) {
    ns_mgr_poll(&mgr, 1000);
  }
  ns_mgr_free(&mgr);
  return 0;
}
```

**Comment by mmikulicic** [comment]
Hi,

The leak is `/etc/hosts` and has been fixed in #192.
We didn't make a new release yet but you can try out the master branch which currently contains bug fixes and minor API updates (there is a new parameter to `ns_connect_http` for post data).
