### ISSUE TITLE
NS_HTTP_REPLY: reassemble HTTP POST payload from chunks

### ISSUE THREAD

**Issue by kkutsner** [cesanta/fossa#240]
When `NS_HTTP_REPLY` arrives and the response body is transferred as chunks the library preserves chunk "markers". So the response's body need to be post-processed to remove all chunk "markers".  Is this something that the library can handle efficiently internally?

**Comment by cpq** [comment]
Yeah that makes sense. Fossa now calls NS_HTTP_REPLY when the whole POST data is buffered. In case of chunked transfer, there could be several ways to go:

1. Introduce NS_HTTP_CHUNK event and `struct http_message :: chunk` field. For each chunk, strip chunk markers and invoke NS_HTTP_CHUNK event. `struct http_message :: chunk` would point to the chunk data.
2. All chunks with stripped markers are concatenated together. When last chunk is received, NS_HTTP_REPLY is invoked, `struct http_message :: body` would point to the whole reassembled body.

**Comment by kkutsner** [comment]
#1: Is it assumed that `struct http_message::body` will be empty in the case of chunked transfer or it will be filled as well when NS_HTTP_REPLY is invoked? I guess if chunk data is removed when handling NS_HTTP_CHUNK on client side then the body should be empty...

#2: Looks simple and easy to use, but in the case of large responses need to implement streaming manually. My understanding that chunked transferring was originally designed to support big unknown size responses so I'd vote for #1

**Comment by cpq** [comment]
Sounds reasonable. Then, NS_HTTP_CHUNK  can reuse `struct http_message::body`, store chunk data there, and discard it after callback invocation.
The only downside I see if client sends chunked POST and server doesn't handle NS_HTTP_CHUNK, it'd miss the POST data in NS_HTTP_REPLY.

**Comment by cpq** [comment]
Rojer, please take this over.

**Comment by cpq** [comment]
Implemented in https://github.com/cesanta/fossa/commit/a21e97e79790d76c24b20c0eb99adbf7579ada73
