### ISSUE TITLE
How to add a serial device in fossa's select loop?

### ISSUE THREAD

**Issue by makoven** [cesanta/fossa#280]
Hello.
I have a serial device (CoolMaster 1000D). I want to write a web interface for it using fossa or mongoose on linux. Can you please tell how to add a tty to select/poll loop, which fossa uses.

**Comment by mmikulicic** [comment]
Hi! 
Despite the name, `ns_add_sock` works with any file descriptor on unices.

**Comment by cpq** [comment]
@makoven , provided that opened serial device is `select()`-able, you can do this:

```
int fd = open(....); // Your serial device
struct ns_connection *nc = ns_add_sock(mgr, fd, my_event_handler);
nc->user_data = "that's my serial device";
```

Could you confirm that that works please?

**Comment by makoven** [comment]
@mmikulicic, @cpq
Thank you. I'll check it later workable and write the results here

**Comment by cpq** [comment]
@makoven , could you elaborate on your results please?

**Comment by makoven** [comment]
@cpq, @mmikulicic 

No, it doesn't work. Function _ns_mgr_poll_ calls _send()_ (not _write()_) to send data to the socket. As a result, in the event NS_SEND i get _ev_data_ equal to -1 and perror "Socket operation on non-socket"

**Comment by schmurfy** [comment]
I also got into this issue, one option might be to add pointers to the function used to read/write into the nc_connection structure, what do you think ? Would it be something you would merge ?
The way the library is designed I don't think there would be much trouble doing this.

PS: fossa is a really nice library

**Comment by mmikulicic** [comment]
Since we always pass 0 as flags to both send and recv, would it make sense to just use write and read (and fallback to send and recv  on platforms that provide only those, e.g. lwip shim layers) ?

**Comment by cpq** [comment]
@mmikulicic yes that might work. We need to find a workaround for windows, cause on win32 `read()` and `recv()` are not interchangeable.

**Comment by schmurfy** [comment]
I did not notice flags were always 0 xD
I swapped recv/send with read/write on my copy and it works great !
Windows is such a pain... If that's only for it why not just handle it with the preprocessor ?

**Comment by mmikulicic** [comment]
Something like
```
#ifdef NS_POSIX
```
?

There might be a bunch of archs that need to use recv/send: windows, lwip based ESP SDK, etc

**Comment by mmikulicic** [comment]
@schmurfy Yes handling with preprocessor is the way to go. 

I'd just like to avoid making too many windows specific stuff, when it's the other way around in this case: most non-POSIX platforms that just embrace the BSD socket API won't have the read/recv write/send equivalence (or likely not even have read and write calls).

**Comment by cpq** [comment]
I'd go for more explicit flag, e.g. `NS_USE_READ_WRITE` - it will be easy to explain that in the doc.

@mmikulicic , would you bake a PR for that pls?

**Comment by mmikulicic** [comment]
should we default on that on linux and osx ?

**Comment by makoven** [comment]
@mmikulicic @cpq 
Thank you very much. Now I can throw a socat out of the project
