### ISSUE TITLE
ns_connect_http() does not encode passed URL

### ISSUE THREAD

**Issue by kkutsner** [cesanta/fossa#289]
Fossa's documentation does not say that passed URL to `ns_connect_http()` routine should be escaped from spaces, etc. If it is by design, I would expect to see a note on documentation or some kind of assertion in the code to warn developers that URL should be encoded before passing. However, it will be nice if `ns_connect_http()` route encodes the passed URL internally.

**Comment by cpq** [comment]
Fixed.
http://cesanta.com/docs/fossa/#_ns_connect_http
