### ISSUE TITLE
ns_connect_http chunked transfer

### ISSUE THREAD

**Issue by harlequin** [cesanta/fossa#291]
I have implemented the ns_connect_http function to receive a file from a web service.
This service has implemented the chunked transfer.

Now inside fossa is no handling for the chunked data.

If you print the hex data of the "mbuf" you are seeing ...

4bf <= Size
..... <= Data

So every packet contains also the size.

Additionaly when the server send the "zero" frame to fossa client, fossa doesn't react on this and doesn't close the connection.

**Comment by cpq** [comment]
Yes we have #240 for handling chunked transfer.
Closing this one as duplicate.
