### ISSUE TITLE
Compilation Errors

### ISSUE THREAD

**Issue by iamttaM** [cesanta/fossa#295]
Converting our code over from Mongoose to Fossa and having a few basic issues compiling Fossa using Visual Studio 2010.

Using the latest source and header - it hasn't been modified. The only define were using is NS_ENABLE_THREADS which seems to be required by default (as spawn_stdio_thread calls ns_start_thread which isn't defined without it).

```
1>  fossa.cpp
1>..\..\..\fossa.cpp(1250): error C2664: 'sendto' : cannot convert parameter 2 from 'const void *' to 'const char *'
1>          Conversion from 'void*' to pointer to non-'void' requires an explicit cast
1>..\..\..\fossa.cpp(1588): error C2664: 'setsockopt' : cannot convert parameter 4 from 'void *' to 'const char *'
1>          Conversion from 'void*' to pointer to non-'void' requires an explicit cast
1>..\..\..\fossa.cpp(2277): error C3861: 'close': identifier not found
1>..\..\..\fossa.cpp(4110): error C3861: 'mkdir': identifier not found
1>..\..\..\fossa.cpp(4141): error C3861: 'rmdir': identifier not found
1>..\..\..\fossa.cpp(4171): error C3861: 'mkdir': identifier not found
1>..\..\..\fossa.cpp(5042): error C3861: '_wopen': identifier not found
1>..\..\..\fossa.cpp(6425): error C2664: 'RegQueryValueExA' : cannot convert parameter 5 from 'char [128]' to 'LPBYTE'
1>          Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
1>..\..\..\fossa.cpp(6427): error C2664: 'RegQueryValueExA' : cannot convert parameter 5 from 'char [128]' to 'LPBYTE'
1>          Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
```

**Comment by AurelienRibon** [comment]
I had the same issue in my project, but it's our fault actually: fossa is designed in C, not C++. Therefore, you need to compile it in C, not C++.

Actually, C allows implicit conversion from void* to char*, which C++ disallows.

I'm using Gradle for my build script, so the correct build is as follows:
https://gist.github.com/AurelienRibon/1fd235c94f4ebcd69122

**Comment by mmikulicic** [comment]
Fossa should be C++ clean, so if it fails to compile standard C++ we'll treat it as a bug.
That said, some issues might not be caused by C++ per se, but could be platform incompatibilities that become visible in C++ due to it's more strict set of typing rules. We do support Windows.

**Comment by iamttaM** [comment]
Thanks for the pointer AurelienRibon - I spotted my mistake. I had imported the file with a .cpp extension rather than .c. Simply renaming it would fix the compilation issues with VS.
