### ISSUE TITLE
Current Cipher-suite is not supported on latest Firefox (ssl_error_no_cypher_overlap)

### ISSUE THREAD

**Issue by AurelienRibon** [cesanta/fossa#296]
When i enable SSL, Firefox cannot display the website and shows the error "ssl_error_no_cypher_overlap". All other browsers work fine.

I solved this by replacing the cipher-suite with the "intermediate recommended one" from Mozilla;
https://wiki.mozilla.org/Security/Server_Side_TLS#Recommended_configurations

It may be interesting to provide a #ifdef to select the cipher suite at compile time.

**Comment by rojer** [comment]
i'll take a look

**Comment by rojer** [comment]
thanks again, Aurelien. this wiki page is exactly what i needed but couldn't find when working on this.
i made "intermediate" the default and added knobs to select "old" or "modern" instead.
a change has been committed to our private dev repo and will hit public on next export.

**Comment by cpq** [comment]
I've pushed to public.
@AurelienRibon could you try the head and confirm the fix please?

**Comment by rojer** [comment]
commit is https://github.com/cesanta/fossa/commit/45fa88e6c77cddecc7cae976c1b7f4736954f041

**Comment by AurelienRibon** [comment]
Works like a charm, thanks guys!
