### ISSUE TITLE
SSL REST client: calling SSL_accept() during handshake

### ISSUE THREAD

**Issue by danielinux** [cesanta/fossa#297]
When a SSL client is initiating the handshake, upon the first event a SSL_accept() gets improperly called, resulting in a SSL fatal error. 

The code responsible for this is in fossa.c:1858

Adding a simple check against conn->flags containing NSF_LISTENING, and setting the flags to NSF_SSL_HANDSHAKE_DONE when actually in client mode, solves the problem for me.

**Comment by cpq** [comment]
Thanks Daniel!
Please sign the CLA https://cesanta.com/contributors_la.shtml and

**Comment by danielinux** [comment]
CLA has been signed, feel free to integrate my code if it does not break the SSL server...

**Comment by cpq** [comment]
Pushed
https://github.com/cesanta/fossa/commit/423a10cdd99de11649ce4f0229f79c168411621f
https://github.com/cesanta/fossa/commit/b84e380c43ad7ca987b6e3539cfe872c6c7ef0e7

Thank you @danielinux !

**Comment by cpq** [comment]
Yeah, please reopen if that doesn't work for you!
