### ISSUE TITLE
Fossa fails to link without NS_DISABLE_PFS switch on Windows

### ISSUE THREAD

**Issue by grodansparadis** [cesanta/fossa#308]
I get unresolved externals as of below when I try to compile fossa on windows with NS_ENABLE_SSL. They are related to PFS (links if NS_DISABLE_PFS defined). Lib used is oppenssl  1.0.2d. ssleay

Do I need to link to any more lib for this functionality and if so which?

Cheers
/Ake

fossa.obj : error LNK2019: unresolved external symbol _BIO_new_file referenced in function _ns_use_cert
1>fossa.obj : error LNK2019: unresolved external symbol _BIO_free referenced in function _ns_use_cert
1>fossa.obj : error LNK2019: unresolved external symbol _BIO_new_mem_buf referenced in function _ns_use_cert
1>fossa.obj : error LNK2019: unresolved external symbol _DH_free referenced in function _ns_use_cert
1>fossa.obj : error LNK2019: unresolved external symbol _PEM_read_bio_DHparams referenced in function _ns_use_cert
1>.\Debug/vscphelper.dll : fatal error LNK1120: 5 unresolved externals

**Comment by cpq** [comment]
@rojer could you address it please?

**Comment by cpq** [comment]
@grodansparadis what openssl libs are you linking against?

**Comment by grodansparadis** [comment]
I use a precompiled lib from http://slproweb.com/products/Win32OpenSSL.html

**Comment by rojer** [comment]
which version - 1.0.2 or 0.9.8?

**Comment by grodansparadis** [comment]
1.0.2d

Den 2015-09-04 kl. 08:51, skrev rojer:
>
> which version - 1.0.2 or 0.9.8?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cesanta/fossa/issues/308#issuecomment-137660727>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org

**Comment by rojer** [comment]
BIO functions seem to be in the `libeay32.dll` lib, can you link against that too?

**Comment by grodansparadis** [comment]
Thanks, that solves it.

Den 2015-09-04 kl. 09:06, skrev rojer:
>
> BIO functions seem to be in the |libeay32.dll| lib, can you link 
> against that too?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cesanta/fossa/issues/308#issuecomment-137662117>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org
