### ISSUE TITLE
Aborted (core dumped)

### ISSUE THREAD

**Issue by MaxSurtaev** [cesanta/fossa#311]
example multi-threaded server has Aborted (core dumped)
compilation with gcc 4.9.2

```
cc multithreaded_restful_server.c ../../fossa.c -o multithreaded_restful_server -W -Wall -I../.. -pthread -DNS_ENABLE_THREADS 
../../fossa.c: In function ‘spawn_handling_thread’:
../../fossa.c:3134:10: warning: missing initializer for field ‘active_connections’ of ‘struct ns_mgr’ [-Wmissing-field-initializers]
   struct ns_mgr dummy = {};
          ^
In file included from ../../fossa.c:1:0:
../../fossa.h:603:25: note: ‘active_connections’ declared here
   struct ns_connection *active_connections;
                         ^

```
running and crash after try to connect with firefox 40.0.3 browser

```
oracle@ub-vm:~/Downloads/fossa-e4bd371337db61c17b809cb123b76dc061ceaf10/examples/multithreaded_restful_server$ ./multithreaded_restful_server 
Starting multi-threaded server on port 8000
epoll_ctl: Invalid argument
Aborted (core dumped)

```

**Comment by cpq** [comment]
Hi Max,
please switch to https://github.com/cesanta/mongoose , since fossa was merged back to mongoose after a long split.
Could you repeat the test under mongoose and report?
Note: Mongoose API is identical to Fossa's now, just API functions and constants were renamed.
Thanks!

**Comment by grodansparadis** [comment]
Sorry for jumping in on this thread. But does this mean they (fossa + 
mongoose) can work together in the same now?

Den 2015-09-21 kl. 09:50, skrev Sergey Lyubka:
> Hi Max,
> please switch to https://github.com/cesanta/mongoose , since fossa was
> merged back to mongoose after a long split.
> Could you repeat the test under mongoose and report?
> Note: Mongoose API is identical to Fossa's now, just API functions and
> constants were renamed.
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cesanta/fossa/issues/311#issuecomment-141900700>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org

**Comment by cpq** [comment]
@grodansparadis Some time ago, TCP networking core was split from mongoose into a separate project - and became fossa. Now, fossa is merging back to mongoose.
Mongoose is essentially replaced by fossa, cause fossa took a more flexible approach with regard of API and protocol support. Old Mongoose API is replaced by a new, Fossa API.

**Comment by grodansparadis** [comment]
Thanks for clearing that. I had the bad luck of doing a lot of for for 
VSCP just before fossa started. Have a bit of work to do not then... 
But thats life. Thanks for a superb work.

Den 2015-09-21 kl. 11:33, skrev Sergey Lyubka:
> @grodansparadis <https://github.com/grodansparadis> Some time ago, TCP
> networking core was split from mongoose into a separate project - and
> became fossa. Now, fossa is merging back to mongoose.
> Mongoose is essentially replaced by fossa, cause fossa took a more
> flexible approach with regard of API and protocol support. Old Mongoose
> API is replaced by a new, Fossa API.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cesanta/fossa/issues/311#issuecomment-141924399>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org

**Comment by MaxSurtaev** [comment]
The same error with https://github.com/cesanta/mongoose
steps for reproducing issue:
1. download https://github.com/cesanta/mongoose/archive/master.zip and unzip mongoose-master.zip
2. go to examples folder and execute make command
3. go into multithreaded_restful_server folder and run it
4. open in browser address localhost:8000
5. app crashes.

**Comment by MaxSurtaev** [comment]
Also, I tested the example simplest_web_server
* added "-DNS_ENABLE_THREADS -pthread"
* added mg_enable_multithreading(nc); after nc = mg_bind(&mgr, s_http_port, ev_handler);

and app crushed with the same error

**Comment by cpq** [comment]
Thanks @MaxSurtaev . What's your environment - OS, primarily?

**Comment by cpq** [comment]
closing this, as this has to move to mongoose.

**Comment by MaxSurtaev** [comment]
I used ubuntu 3.19.0-28-generic #30-Ubuntu SMP  in VirtualBox 5
