### ISSUE TITLE
VC++ 2015 int strnlen

### ISSUE THREAD

**Issue by pavel-pimenov** [cesanta/fossa#313]
https://github.com/cesanta/fossa/blob/master/fossa.h#L437

1>q:\vc15\fly-server-benchmark\http_client\fossa.h(437): error C2556: 'int strnlen(const char *,size_t)': overloaded function differs only by return type from 'size_t strnlen(const char *,size_t)'
1>  c:\program files (x86)\windows kits\10\include\10.0.10240.0\ucrt\string.h(357): note: see declaration of 'strnlen'
1>q:\vc15\fly-server-benchmark\http_client\fossa.h(437): error C2371: 'strnlen': redefinition; different basic types
1>  c:\program files (x86)\windows kits\10\include\10.0.10240.0\ucrt\string.h(357): note: see declaration of 'strnlen'

**Comment by mkmik** [comment]
hi, sorry fossa has been superseded by https://github.com/cesanta/mongoose

```
Note: As of September 21st 2015, Fossa project has been merged back into Mongoose project
```

This repo is only kept for historical reasons
