### ISSUE TITLE
VC++2015 error C4996: 'fileno'

### ISSUE THREAD

**Issue by pavel-pimenov** [cesanta/fossa#314]
1>q:\vc15\fly-server-benchmark\http_client\fossa.c(4047): error C4996: 'fileno': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _fileno. See online help for details.
1>  c:\program files (x86)\windows kits\10\include\10.0.10240.0\ucrt\stdio.h(2450): note: see declaration of 'fileno'
1>q:\vc15\fly-server-benchmark\http_client\fossa.c(4161): error C4996: 'fileno': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _fileno. See online help for details.
1>  c:\program files (x86)\windows kits\10\include\10.0.10240.0\ucrt\stdio.h(2450): note: see declaration of 'fileno'
1>q:\vc15\fly-server-benchmark\http_client\fossa.c(4880): warning C4013: 'rmdir' undefined; assuming extern returning int
1>q:\vc15\fly-server-benchmark\http_client\fossa.c(4944): error C4996: 'fileno': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _fileno. See online help for details.
1>  c:\program files (x86)\windows kits\10\include\10.0.10240.0\ucrt\stdio.h(2450): note: see declaration of 'fileno'

**Comment by mkmik** [comment]
hi, sorry fossa has been superseded by https://github.com/cesanta/mongoose

```
Note: As of September 21st 2015, Fossa project has been merged back into Mongoose project
```

This repo is only kept for historical reasons
