### ISSUE TITLE
VC++ 2015 struct ns_mgr dummy = {};

### ISSUE THREAD

**Issue by pavel-pimenov** [cesanta/fossa#315]
1>q:\vc15\fly-server-benchmark\http_client\fossa.c(3134): error C2059: syntax error: '}'

fix

--- fossa.c (revision 53)
+++ fossa.c (working copy)
@@ -3131,7 +3131,7 @@
 }

 static void spawn_handling_thread(struct ns_connection *nc) {
-  struct ns_mgr dummy = {};
-  struct ns_mgr dummy = {0};
  sock_t sp[2];
  struct ns_connection *c[2];

**Comment by mkmik** [comment]
hi, sorry fossa has been superseded by https://github.com/cesanta/mongoose

```
Note: As of September 21st 2015, Fossa project has been merged back into Mongoose project
```

This repo is only kept for historical reasons
